# cfg.py
HOST = "irc.chat.twitch.tv"              # the Twitch IRC server
PORT = 6667                         # always use port 6667
NICK = "lautrecbot"            # your Twitch username, lowercase
PASS = "REDACTED" # your Twitch OAuth token
CHAN = "#REDACTED"                   # the channel you want to join
RATE = (100/30)                  #messages per second
NUM_MESSAGES = 200                     #number of chat messages between Lautrec messages
PUNCTUATION = ['.','!','?', ',']
LAUTREC = [
'Oh, still human are you?',
'Then I am in luck. Could you help me?',
'As you can see I am stuck, without recourse.',
'Please, I have duties to fulfil, and I will reward you handsomely.',
'Well? I am certain you stand to benefit.',
'Why! You!',
'Do not run away! Hear me out!',
'Ahh, you have come back.',
'I beg of you. Help me.',
'Thank you, yes, sincerely.',
'I am Knight Lautrec of Carim.',
'I truly appreciate this, and I guarantee a reward, only later.',
'Yes, very sorry, but your reward will have to wait.',
'I have just been freed. Allow me some time.',
'I am free. Now I can get back to work…',
'Keh heh heh heh…',
'Well, what have we here?',
'Keh keh keh. Are you sure about this?',
'When attacked and made hostile',
'You leave me no choice.',
'I was once grateful to you.',
'But if this is our fate, so be it!',
'You despicable…',
'Curses… How could I…',
'Ahh, hello there…',
'I have your reward. Please accept it.',
'I am grateful to you for freeing me.',
'Keh heh heh heh…',
'… Not enough for you? Well, let\'s not be greedy, now…',
'Keh heh heh heh…',
'Hello… I don\'t think we\'ve met.',
'I am Knight Lautrec of Carim.',
'We are both Undead. Perhaps we can help one another.',
'Keh heh heh heh…',
'Hmm, what business do you have?',
'If you have none, then stay silent.',
'…You…',
'How dare you come prancing about!',
'I have nothing to say. Be gone from my sight.',
'Ah, you certainly are keeping busy.',
'Care to pay for a useful tip?',
'A wise choice, indeed.',
'Oh, really?',
'Well, suit yourself. Only trying to help.',
'Hm? That tip I gave you? Ahh, I heard it from a fleeing old man.',
'That poor bastard! All his robes and trinkets won\'t help him now!',
'Kwah hah hah hah hah!',
'Have you heard of Trusty Patches?',
'If ever a man has rubbed me up the wrong way, ugh!',
'If he ever comes around again, I swear, I\'ll have his hide.',
'By the lords… Your face…',
'Hmm… Your humanity is really slipping.',
'But there are methods. Most fools have more humanity than they know what to do with.',
'Now, who do you imagine will make the best use of it, hmm?',
'Well, where have you been?',
'I am glad to see you are safe.',
'Oh, hello.',
'I\'m considering a change of location…',
'I have a rather, pressing matter to attend to up above.',
'That Keeper has served me well, but… enough with her…',
'Keh heh heh heh…',
'Hm, you again? What is it?',
'Our futures are murky. Let\'s not be too friendly, now',
'Well, look at you.',
'I thought you were wiser, but I thought wrong!',
'Tis a terrible pity. Like a moth flittering towards a flame.',
'You fellows? No? Don\'t you agree?',
'When you enter his aggro range, after the first time',
'So, here we go again!',
'How many times will these lambs rush to slaughter?',
'Well, let\'s get it over with.'
]

NOUNS = [
            'enemy',
            'monster',
            'mob enemy',
            'tough enemy',
            'critical foe',
            'hollow',
            'pilgrim',
            'prisoner',
            'monstrosity',
            'skeleton',
            'ghost',
            'beast',
            'lizard',
            'bug',
            'grub',
            'crab',
            'dwarf',
            'giant',
            'demon',
            'dragon',
            'knight',
            'sellword',
            'warrior',
            'herald',
            'bandit',
            'assassin',
            'sorcerer',
            'pyromancer',
            'cleric',
            'deprived',
            'sniper',
            'duo',
            'trio',
            'you',
            'you bastard',
            'good fellow',
            'saint',
            'wretch',
            'charmer',
            'poor soul',
            'oddball',
            'nimble one',
            'laggard',
            'moneybags',
            'beggar',
            'miscreant',
            'liar',
            'fatty',
            'beanpole',
            'youth',
            'elder',
            'old codger',
            'old dear',
            'merchant',
            'artisan',
            'master',
            'sage',
            'champion',
            'lord of cinder',
            'king',
            'queen',
            'prince',
            'princess',
            'angel',
            'god',
            'friend',
            'ally',
            'spouse',
            'covenantor',
            'phantom',
            'dark spirit',
            'bonfire',
            'ember',
            'fog wall',
            'lever',
            'contraption',
            'key',
            'trap',
            'torch',
            'door',
            'treasure',
            'chest',
            'something',
            'quite something',
            'rubbish',
            'filth',
            'weapon',
            'shield',
            'projectile',
            'armor',
            'item',
            'ring',
            'ore',
            'coal',
            'transposing kiln',
            'scroll',
            'umbral ash',
            'throne',
            'rite',
            'coffin',
            'cinder',
            'ash',
            'moon',
            'eye',
            'brew',
            'soup',
            'message',
            'bloodstain',
            'illusion',
            'close-ranged battle',
            'ranged battle',
            'eliminating one at a time',
            'luring it out',
            'beating to a pulp',
            'ambush',
            'pincer attack',
            'hitting them in one swoop',
            'duel-wielding',
            'stealth',
            'mimicry',
            'fleeing',
            'charging',
            'jumping off',
            'dashing through',
            'circling around',
            'trapping inside',
            'rescue',
            'skill',
            'sorcery',
            'pyromancy',
            'miracles',
            'pure luck',
            'prudence',
            'brief respite',
            'play dead',
            'jog',
            'dash',
            'rolling',
            'backstepping',
            'jumping',
            'attacking',
            'jump attack',
            'dash attack',
            'counter attack',
            'stabbing in the back',
            'guard stun & stab',
            'plunging attack',
            'shield breaking',
            'blocking',
            'parrying',
            'locking-on',
            'no lock-on',
            'two-handing',
            'gesture',
            'control',
            'destroy',
            'boulder',
            'lava',
            'poison gas',
            'enemy horde',
            'forest',
            'swamp',
            'cave',
            'shortcut',
            'detour',
            'hidden path',
            'secret passage',
            'dead end',
            'labyrinth',
            'hole',
            'bright spot',
            'dark spot',
            'open area',
            'tight spot',
            'safe zone',
            'danger zone',
            'sniper spot',
            'hiding place',
            'illusory wall',
            'ladder',
            'lift',
            'gorgeous view',
            'looking away',
            'overconfidence',
            'slip-up',
            'oversight',
            'fatigue',
            'bad luck',
            'inattention',
            'loss of stamina',
            'chance encounter',
            'planned encounter',
            'front',
            'back',
            'left',
            'right',
            'up',
            'down',
            'below',
            'above',
            'behind',
            'head',
            'neck',
            'stomach',
            'back',
            'armor',
            'finger',
            'leg',
            'rear',
            'tail',
            'wings',
            'anywhere',
            'tongue',
            'right arm',
            'left arm',
            'thumb',
            'indexfinger',
            'longfinger',
            'ringfinger',
            'smallfinger',
            'right leg',
            'left leg',
            'right side',
            'left side',
            'pincer',
            'wheel',
            'core',
            'mount',
            'regular',
            'strike',
            'thrust',
            'slash',
            'magic',
            'crystal',
            'fire',
            'chaos',
            'lightning',
            'blessing',
            'dark',
            'critical hits',
            'bleeding',
            'poison',
            'toxic',
            'frost',
            'curse',
            'equipment breakage',
            'chance',
            'quagmire',
            'hint',
            'secret',
            'sleeptalk',
            'happiness',
            'misfortune',
            'life',
            'death',
            'demise',
            'joy',
            'fury',
            'agony',
            'sadness',
            'tears',
            'loyalty',
            'betrayal',
            'hope',
            'despair',
            'fear',
            'losing sanity',
            'victory',
            'defeat',
            'sacrifice',
            'light',
            'dark',
            'bravery',
            'confidence',
            'vigor',
            'revenge',
            'resignation',
            'overwhelming',
            'regret',
            'pointless',
            'man',
            'woman',
            'friendship',
            'love',
            'recklessness',
            'composure',
            'guts',
            'comfort',
            'silence',
            'deep',
            'dregs',
            'good luck',
            'fine work',
            'i did it',
            'i\'ve failed',
            'here',
            'not here',
            'i can\'t take this',
            'lonely',
            'don\'t you dare',
            'do it',
            'look carefully',
            'listen carefully',
            'think carefully',
            'this place again',
            'now the real fight begins',
            'you don\'t deserve this',
            'keep moving',
            'pull back',
            'give it up',
            'don\'t give up',
            'help me',
            'impossible',
            'bloody expensive',
            'let me out of here',
            'stay calm',
            'like a dream',
            'seems familiar',
            'are you ready',
            'it\'ll happen to you too',
            'praise the sun',
            'may the flames guide thee',
'you\'ve come to the right place',
'bless us with blood',
'may the good blood guide your way',
'fear your blindness',
'the sky and the cosmos are one',
'let us cleanse these foul streets',
'you\'re in the know right',
'oh i can\'t wait hee hee',
'take a step forward',
'turn back',
'those with faith will be spared',
'don\'t be fooled',
'pitiful really',
'behind you',
'don\'t you dare look at me',
'sincerest thanks',
'a hunter is never alone',
'please carry on in my stead',
'run',
'man-beast',
'giant beast',
'abhorrent beast',
'infected one',
'foe',
'strong foe',
'giant foe',
'terrible foe',
'hound',
'bird',
'snake',
'animal',
'insect',
'watcher',
'shaman',
'dead',
'foul spirit',
'the lost',
'malformed thing',
'unknown thing',
'slimy thing',
'blobby thing',
'kin of the cosmos',
'evil eye',
'false god',
'superior being',
'messenger',
'doll',
'elderly',
'ailing one',
'madman',
'keeper',
'mob',
'wheelchair',
'small gent',
'small lady',
'titan',
'amazon',
'dullard',
'scoundrel',
'child',
'darling',
'infant',
'yourself',
'hunter',
'cooperator',
'adversary',
'executioner',
'vileblood',
'hunter of hunters',
'blood-addled hunter',
'physical attack',
'blunt attack',
'thrust attack',
'blood attack',
'arcane',
'bolt',
'quick weapon',
'long weapon',
'frenzy',
'exploiting species',
'beast transformation',
'firearm',
'blunderbuss',
'rally',
'charge attack',
'visceral attack',
'quickstep',
'blood vial',
'quicksilver bullet',
'medicine',
'special medicine',
'oil',
'coarse paper',
'special item',
'\"focus on attacks\"',
'sneak attack',
'patrol',
'reinforcements caller',
'\"focus on evasion\"',
'\"focus on healing\"',
'\"close-range fight\"',
'\"long-range fight\"',
'\"hit-and-run\"',
'sniping',
'counter',
'\"attack from behind\"',
'\"open when attacking\"',
'\"strike and be struck\"',
'\"kill in order\"',
'\"kill first\"',
'charging forth',
'lure',
'ignoring',
'retreat',
'use of terrain',
'high spot',
'fall',
'alertness',
'unbreakable will',
'leaden constitution',
'blood echoes',
'insight',
'bloodstone',
'blood gem',
'rune',
'ritual material',
'paleblood',
'rating',
'dead body',
'statue',
'footing',
'yharnam',
'clinic',
'grand cathedral',
'church',
'safe place',
'old labyrinth',
'workshop',
'healing church',
'unseen village',
'hunting',
'night',
'dawn',
'blood',
'warm blood',
'scourge',
'nightmare',
'cosmos',
'oedon',
'communion',
'donation',
'ritual',
'contact',
'encounter',
'evolution',
'oath',
'corruption',
'execution',
'cleansing',
'prayer',
'defilement',
'sinister',
'courage',
'respect',
'inquisitiveness',
'pity',
'grief',
'wrath',
'sanity',
'madness',
'fervor',
'seduction',
'feasting',
'tastiness',
'tonsil',
'metamorphosis',
'common sense',
'darkness',
'singing',
'sobbing',
'howling',
'\"all\'s well\"',
'the unseen',
'all'
]

TEMPLATES = [
        'no **** ahead',
        'be wary of ****',
        'try ****',
        'could this be a ****',
        'if only i had a ****',
        'could this be an ****',
        'if only i had an ****',
        'visions of ****',
        'time for ****',
        'huh it\'s a ****',
        'huh it\'s an ****',
        'praise the ****',
        'let there be ****',
        'ahh ****',
        '**** waits ahead',
        'beware of ****',
        'it\'s the scourge of ****',
        'fear ****',
        'need ****',
        'reeks of ****',
        'remember ****',
        'despicable ****',
        'woeful ****',
        'wondrous ****',
        'weakness: ****',
        'you must accept ****',
        'treat **** with care',
        'nothing but **** here',
        'it is all thanks to ****',
        'imminent ****',
        'have mercy ****',
        'no mercy for ****',
        'have audience with ****',
        'reminiscent of ****',
        'hurrah for ****',
        'oh ****',
        '**** is effective',
        '**** required ahead',
        '**** ahead',
        '****'
]

CONJUNCTIONS = [
        ' and then ',
        ' therefore ',
        ' eventually ',
        ' in short ',
        ' or ',
        ' by the way ',
        ' so to speak ',
        ' all the more ',
        ' however '
]